---
name: Build and test app
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Dockerhub
        id: Login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        id: Build
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/flask-app-gh-actions
      - name: Push Docker image
        id: push
        run: docker push ${{secrets.DOCKER_USER}}/flask-app-gh-actions


